pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      mirror: "https://docker-registry-mirror.redpencil.io"
      repo: "${CI_REPO_OWNER%%io}/${CI_REPO_NAME}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: feature/*
