pipeline:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      mirror: "https://docker-registry-mirror.redpencil.io"
      registry: "oci.redpencil.io"
      repo: "oci.redpencil.io/${CI_REPO_OWNER%%io}/${CI_REPO_NAME}"
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: feature/*
